"""
Database & Security Sentinel Module
Generated by IBM Bob 2.0 Subagent
Mitigations:
- 100% Parameterized queries (Zero SQL Injection)
- Atomic transactions with rollback protection
"""

import sqlite3
from datetime import datetime

class DatabaseManager:
    def __init__(self, db_path="modern_store.db"):
        self.db_path = db_path
        self.init_db()

    def get_connection(self):
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        return conn

    def init_db(self):
        with self.get_connection() as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS inventory (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    item_name TEXT NOT NULL,
                    quantity INTEGER NOT NULL CHECK (quantity >= 0),
                    unit_price REAL NOT NULL,
                    updated_at TEXT NOT NULL
                )
            """)
            conn.execute("""
                CREATE TABLE IF NOT EXISTS orders (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    customer_name TEXT NOT NULL,
                    item_id INTEGER NOT NULL,
                    qty INTEGER NOT NULL,
                    total_price REAL NOT NULL,
                    order_date TEXT NOT NULL,
                    FOREIGN KEY (item_id) REFERENCES inventory(id)
                )
            """)
            conn.commit()

    def add_item(self, name: str, quantity: int, unit_price: float) -> int:
        timestamp = datetime.utcnow().isoformat()
        with self.get_connection() as conn:
            cursor = conn.cursor()
            cursor.execute(
                "INSERT INTO inventory (item_name, quantity, unit_price, updated_at) VALUES (?, ?, ?, ?)",
                (name, quantity, unit_price, timestamp)
            )
            conn.commit()
            return cursor.lastrowid

    def search_items(self, search_term: str):
        with self.get_connection() as conn:
            cursor = conn.cursor()
            cursor.execute(
                "SELECT * FROM inventory WHERE item_name LIKE ?",
                (f"%{search_term}%",)
            )
            return [dict(row) for row in cursor.fetchall()]

    def process_order(self, customer_name: str, item_id: int, order_qty: int):
        with self.get_connection() as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT quantity, unit_price FROM inventory WHERE id = ?", (item_id,))
            item = cursor.fetchone()

            if not item:
                return False, "Item not found"

            current_qty, price = item["quantity"], item["unit_price"]
            if current_qty < order_qty:
                return False, "Insufficient inventory stock"

            # Atomic deduction and order record
            new_qty = current_qty - order_qty
            total = order_qty * price
            order_date = datetime.utcnow().isoformat()

            cursor.execute("UPDATE inventory SET quantity = ? WHERE id = ?", (new_qty, item_id))
            cursor.execute(
                "INSERT INTO orders (customer_name, item_id, qty, total_price, order_date) VALUES (?, ?, ?, ?, ?)",
                (customer_name, item_id, order_qty, total, order_date)
            )
            conn.commit()
            return True, "Order completed successfully"
