"""
Automated Pytest Suite
Generated by IBM Bob 2.0 Subagent (Autonomous Test Engine)
Verifies: Edge cases, zero regressions, and SQL injection safety
"""

import os
import pytest
from models import DatabaseManager

TEST_DB = "test_modern_store.db"

@pytest.fixture
def db():
    if os.path.exists(TEST_DB):
        os.remove(TEST_DB)
    manager = DatabaseManager(TEST_DB)
    yield manager
    if os.path.exists(TEST_DB):
        os.remove(TEST_DB)

def test_add_and_search_inventory(db):
    item_id = db.add_item("Industrial Sensor", 50, 99.95)
    assert item_id == 1

    results = db.search_items("Sensor")
    assert len(results) == 1
    assert results[0]["item_name"] == "Industrial Sensor"
    assert results[0]["quantity"] == 50

def test_sql_injection_defense(db):
    # Attempting SQL injection payload
    malicious_payload = "Sensor' OR '1'='1"
    results = db.search_items(malicious_payload)
    # Parameterized query must treat it as literal string, returning 0 results safely
    assert len(results) == 0

def test_order_stock_deduction_and_insufficient_stock(db):
    item_id = db.add_item("Relay Switch", 10, 15.0)
    
    # Successful order
    success, msg = db.process_order("Devendra", item_id, 4)
    assert success is True
    
    # Check remaining stock
    items = db.search_items("Relay Switch")
    assert items[0]["quantity"] == 6

    # Exceeding stock order
    fail_success, fail_msg = db.process_order("Devendra", item_id, 20)
    assert fail_success is False
    assert "Insufficient" in fail_msg
